name: release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          curl -L -o mpv-uosc.zip https://github.com/mpv-easy/mpv-easy/releases/latest/download/mpv-uosc-windows-full.zip
          rm -rf mpv-uosc.zip

          unzip mpv-uosc.zip -d mpv-uosc

          cp autosave.lua mpv-uosc/portable_config/scripts/autosave.lua
          cd mpv-uosc

          zip -r -q ../mpv-uosc.zip .

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "mpv-uosc.zip"
          allowUpdates: true
